install.packages("MASS")
install.packages("lsr")
install.packages("rpart")
install.packages("rpart.plot")
install.packages("Hmisc")
install.packages("pdp")
install.packages("xts")
install.packages("sp")
install.packages("zoo")
install.packages("CASdatasets", repos = "http://cas.uqam.ca/pub/", type="source")